_shortener_api_bundle:
    resource: "@UrlShortenerBundle/Resources/config/routing.yml"

_ecentria_rest_bundle:
    resource: "@EcentriaRestBundle/Resources/config/routing.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/v1/doc