shortener:
    type:     rest
    prefix:   /api/v1/
    resource: "@UrlShortenerBundle/Resources/config/routing/api.yml"
    defaults:
        _format: json

shortener_api_url:
    resource: Rz\Bundle\UrlShortenerBundle\Controller\UrlController
