parameters:
    app.url.shortener.class: AppBundle\Services\Shortener
    app.url.encoder.base.class: AppBundle\Services\Encoder\Base
    app.url.converter.url.class: AppBundle\Services\Converter\UrlConverter
    app.url.listeners.stats.class: AppBundle\EventListener\StatsListener
    app.url.listeners.message.class: AppBundle\EventListener\MessageListener

services:
    app.url.encoder.base:
        class: %app.url.encoder.base.class%

    app.url.shortener:
        class: %app.url.shortener.class%
        arguments:
            - @app.url.encoder.base
            - @router.default
            - @doctrine.orm.default_entity_manager
            - @event_dispatcher

    app.url.converter.url:
        class: %app.url.converter.url.class%
        arguments:
            - @jms_serializer.serializer
        tags:
            - { name: request.param_converter, converter: app.url.converter.url }

    app.url.listeners.stats:
        class: %app.url.listeners.stats.class%
        tags:
            - { name: kernel.event_listener, event: app.url.events.notify, method: notify }

    app.url.listeners.message:
        class: %app.url.listeners.message.class%
        tags:
            - { name: kernel.event_listener, event: app.url.events.notify, method: notify }
